// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zggeujmenxrwhnczqhmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnZ2V1am1lbnhyd2huY3pxaG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTU3NDQsImV4cCI6MjA2NTc3MTc0NH0.tP--psoPbxEqEUTzKXT_9jt0wZzSy8gzFwXadMcS-mQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);